name: polar_example
description: Demonstrates how to use the polar plugin.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  polar:
    path: ../

  uuid: ^4.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  rexios_lints: ^6.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
